# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoUdap < Formula
  desc "Squeezebox UDAP configuration tool"
  homepage "https://github.com/yo61/go-udap"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yo61/go-udap/releases/download/v1.1.0/go-udap_1.1.0_macos_x86_64.tar.gz"
      sha256 "443263d4159a495c47d3022315cb5993990447408f1d218d458977efc6f3c81d"

      define_method(:install) do
        bin.install "go-udap"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yo61/go-udap/releases/download/v1.1.0/go-udap_1.1.0_macos_arm64.tar.gz"
      sha256 "751e77a38aef24dc7e42cc5ca266ecbee54bc49bd4329f21f39d6e2803c55d2c"

      define_method(:install) do
        bin.install "go-udap"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yo61/go-udap/releases/download/v1.1.0/go-udap_1.1.0_linux_x86_64.tar.gz"
      sha256 "9a2061a8a43e14affeed848bae29c92bfba0ebfaeeb43121e8255fb778d2774b"
      define_method(:install) do
        bin.install "go-udap"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yo61/go-udap/releases/download/v1.1.0/go-udap_1.1.0_linux_arm64.tar.gz"
      sha256 "d045ebe1cdaa5618d738f12987e9ae072e2e23506b19ba5166c7d1b436c6e3fb"
      define_method(:install) do
        bin.install "go-udap"
      end
    end
  end

  test do
    assert_match "go-udap", shell_output("#{bin}/go-udap --version")
    assert_match "Usage:", shell_output("#{bin}/go-udap --help")
    assert_match "unknown command", shell_output("#{bin}/go-udap floop 2>&1", 1)
  end
end
