# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoUdap < Formula
  desc "Squeezebox UDAP configuration tool"
  homepage "https://github.com/yo61/go-udap"
  version "1.0.2-rc.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yo61/go-udap/releases/download/v1.0.2-rc.1/go-udap_1.0.2-rc.1_macos_x86_64.tar.gz"
      sha256 "ae63fbc948fc641de78910a26e64a2afa35c130741aa828fdb253c220fa685dd"

      define_method(:install) do
        bin.install "go-udap"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yo61/go-udap/releases/download/v1.0.2-rc.1/go-udap_1.0.2-rc.1_macos_arm64.tar.gz"
      sha256 "5140d871e92299fbc33f94ac0ff1f5667e234dd4b3ea569d5372655ed9240a37"

      define_method(:install) do
        bin.install "go-udap"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yo61/go-udap/releases/download/v1.0.2-rc.1/go-udap_1.0.2-rc.1_linux_x86_64.tar.gz"
      sha256 "5f7923726de9e9145118554a88f467ad470923d8ae62787fa089bd9194c3cea6"
      define_method(:install) do
        bin.install "go-udap"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yo61/go-udap/releases/download/v1.0.2-rc.1/go-udap_1.0.2-rc.1_linux_arm64.tar.gz"
      sha256 "723244dec24f6e41794a8f44ed2cde1e1b1a5ae0ed8de67f3a9309fb77fd216f"
      define_method(:install) do
        bin.install "go-udap"
      end
    end
  end

  test do
    assert_match "go-udap", shell_output("#{bin}/go-udap --version")
    assert_match "Usage:", shell_output("#{bin}/go-udap --help")
    assert_match "unknown command", shell_output("#{bin}/go-udap floop 2>&1", 1)
  end
end
