# This file was generated by GoReleaser. DO NOT EDIT.
cask "go-udap" do
  version "1.5.0"

  on_macos do
    on_intel do
      sha256 "9dc3eae4d798c14227f18ea30f60874e90f2e93f03fd589ea9160b162fc90826"
      url "https://github.com/yo61/go-udap/releases/download/v#{version}/go-udap_#{version}_macos_x86_64.tar.gz",
        verified: "github.com/yo61/go-udap"
    end
    on_arm do
      sha256 "20ca215229b5cf378fc0ddb74780ac95ba4ec8ca861736e862e232c63efdd49d"
      url "https://github.com/yo61/go-udap/releases/download/v#{version}/go-udap_#{version}_macos_arm64.tar.gz",
        verified: "github.com/yo61/go-udap"
    end
  end

  on_linux do
    on_intel do
      sha256 "b8aeb6a3a4ecda89396492e36478374474f76776c913056ee44c07b9d985ebc4"
      url "https://github.com/yo61/go-udap/releases/download/v#{version}/go-udap_#{version}_linux_x86_64.tar.gz",
        verified: "github.com/yo61/go-udap"
    end
    on_arm do
      sha256 "2733c908a950ac7b0700d16fc0a6f2d65cec1affdd3cdf225e3a230dd65544e3"
      url "https://github.com/yo61/go-udap/releases/download/v#{version}/go-udap_#{version}_linux_arm64.tar.gz",
        verified: "github.com/yo61/go-udap"
    end
  end

  name "go-udap"
  desc "Squeezebox UDAP configuration tool"
  homepage "https://github.com/yo61/go-udap"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "go-udap"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/go-udap"]
    end
  end

  # No zap stanza required

end
