# This file was generated by GoReleaser. DO NOT EDIT.
cask "go-udap" do
  version "1.3.3"

  on_macos do
    on_intel do
      sha256 "26edf5b5dd72fa45ad05369ceeb7949a98b9fb915f3bf3e499804aa6ee87b20b"
      url "https://github.com/yo61/go-udap/releases/download/v#{version}/go-udap_#{version}_macos_x86_64.tar.gz",
        verified: "github.com/yo61/go-udap"
    end
    on_arm do
      sha256 "79b589056f109ec3d6e8b4f4185ab615dd20cfe3537f845b0b82c4d12b916010"
      url "https://github.com/yo61/go-udap/releases/download/v#{version}/go-udap_#{version}_macos_arm64.tar.gz",
        verified: "github.com/yo61/go-udap"
    end
  end

  on_linux do
    on_intel do
      sha256 "eded72a6efeb3cd8a885da98146ebf5221322e48373661efaa391f23f0350645"
      url "https://github.com/yo61/go-udap/releases/download/v#{version}/go-udap_#{version}_linux_x86_64.tar.gz",
        verified: "github.com/yo61/go-udap"
    end
    on_arm do
      sha256 "295c396140099d0b22c39aeb229267182b4e6bcc1f38190dd78ebf4e0f20556a"
      url "https://github.com/yo61/go-udap/releases/download/v#{version}/go-udap_#{version}_linux_arm64.tar.gz",
        verified: "github.com/yo61/go-udap"
    end
  end

  name "go-udap"
  desc "Squeezebox UDAP configuration tool"
  homepage "https://github.com/yo61/go-udap"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "go-udap"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/go-udap"]
    end
  end

  # No zap stanza required

end
