# This file was generated by GoReleaser. DO NOT EDIT.
cask "go-udap" do
  version "2.4.6"

  on_macos do
    on_intel do
      sha256 "e45a5cd7c9f5631ceeb3a17ba6aea5ecbdadd2f6510a859aba082911aad13570"
      url "https://github.com/yo61/go-udap/releases/download/v#{version}/go-udap_#{version}_macos_x86_64.tar.gz"
    end
    on_arm do
      sha256 "888f6d9fc9ae6b833157c7a7455bb05633ed52f7ad6475a28fb453600eca07e7"
      url "https://github.com/yo61/go-udap/releases/download/v#{version}/go-udap_#{version}_macos_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "58e95e4b0da7380d2d415bd2d0e0567bf951c5302656ba592327b180e7698c52"
      url "https://github.com/yo61/go-udap/releases/download/v#{version}/go-udap_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "afd625c21847220096461ab3ec82b190162c097f2c9eb90ad59405a977923ad0"
      url "https://github.com/yo61/go-udap/releases/download/v#{version}/go-udap_#{version}_linux_arm64.tar.gz"
    end
  end

  name "go-udap"
  desc "Squeezebox UDAP configuration tool"
  homepage "https://github.com/yo61/go-udap"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "go-udap"
  manpage "share/man/man1/go-udap-discover.1"
  manpage "share/man/man1/go-udap-get.1"
  manpage "share/man/man1/go-udap-getip.1"
  manpage "share/man/man1/go-udap-info.1"
  manpage "share/man/man1/go-udap-interfaces.1"
  manpage "share/man/man1/go-udap-read.1"
  manpage "share/man/man1/go-udap-reboot.1"
  manpage "share/man/man1/go-udap-set.1"
  manpage "share/man/man1/go-udap.1"
  bash_completion "completions/go-udap.bash"
  fish_completion "completions/go-udap.fish"
  zsh_completion "completions/_go-udap"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/go-udap"] if OS.mac?
  end

  # No zap stanza required
end
