# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoUdap < Formula
  desc "Squeezebox UDAP configuration tool"
  homepage "https://github.com/yo61/go-udap"
  version "1.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yo61/go-udap/releases/download/v1.1.1/go-udap_1.1.1_macos_x86_64.tar.gz"
      sha256 "e80b96f30a18a551811de129433490d36993336e67e517e6fe676e32b0d71da1"

      define_method(:install) do
        bin.install "go-udap"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yo61/go-udap/releases/download/v1.1.1/go-udap_1.1.1_macos_arm64.tar.gz"
      sha256 "c4804b212ee51120cffcd18929bbb783bce4978ebd291f688e9a5dde5f57b13c"

      define_method(:install) do
        bin.install "go-udap"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yo61/go-udap/releases/download/v1.1.1/go-udap_1.1.1_linux_x86_64.tar.gz"
      sha256 "c766c7b789aebf5ebfbc60a4e2f4ca5aaaf5f82baa92d3585ba37491772f885c"
      define_method(:install) do
        bin.install "go-udap"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yo61/go-udap/releases/download/v1.1.1/go-udap_1.1.1_linux_arm64.tar.gz"
      sha256 "4a2cd14b9d02026f757ef359e304e04cb35255ba1c709c8458f7755d36432acb"
      define_method(:install) do
        bin.install "go-udap"
      end
    end
  end

  test do
    assert_match "go-udap", shell_output("#{bin}/go-udap --version")
    assert_match "Usage:", shell_output("#{bin}/go-udap --help")
    assert_match "unknown command", shell_output("#{bin}/go-udap floop 2>&1", 1)
  end
end
